# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "VM1-ELIAS" do |vm1elias|
    vm1elias.vm.box = "ubuntu/jammy64"
    vm1elias.vm.hostname = "vm1elias"
    vm1elias.vm.network "private_network", :name => '', ip: "192.168.56.4"
    
    # Comparto la carpeta del host donde estoy parado contra la vm
    vm1elias.vm.synced_folder 'compartido_Host1/', '/home/vagrant/compartido', 
    owner: 'vagrant', group: 'vagrant' 

      # Agrega la key Privada de ssh en .vagrant/machines/default/virtualbox/private_key
      vm1elias.ssh.insert_key = true
      # Agrego un nuevo disco 
      vm1elias.vm.disk :disk, size: "5GB", name: "#{vm1elias.vm.hostname}_extra_storage"
      vm1elias.vm.disk :disk, size: "3GB", name: "#{vm1elias.vm.hostname}_extra_storage2"
      vm1elias.vm.disk :disk, size: "2GB", name: "#{vm1elias.vm.hostname}_extra_storage3"
      vm1elias.vm.disk :disk, size: "1GB", name: "#{vm1elias.vm.hostname}_extra_storage4"

      vm1elias.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "vm1elias"
        vb.cpus = 1
        vb.linked_clone = true
        # Seteo controladora Grafica
        vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']      
      end    
      # Puedo Ejecutar un script que esta en un archivo
      vm1elias.vm.provision "shell", path: "script_Enable_ssh_password.sh"
      vm1elias.vm.provision "shell", path: "instala_paquetes.sh"
      vm1elias.vm.provision "shell", privileged: false, inline: <<-SHELL
      # Los comandos aca se ejecutan como vagrant
  
      mkdir -p /home/vagrant/repogit
      cd /home/vagrant/repogit
      git clone https://github.com/upszot/UTN-FRA_SO_onBording.git 
      git clone https://github.com/upszot/UTN-FRA_SO_Ansible.git
      git clone https://github.com/upszot/UTN-FRA_SO_Docker.git

    SHELL
    end
    
    
    config.vm.define "VM2-ELIAS" do |vm2elias|
      vm2elias.vm.box = "generic/fedora28"
      vm2elias.vm.hostname = "vm2elias"
      vm2elias.vm.network "private_network", :name => '', ip: "192.168.56.5"
      
      # Comparto la carpeta del host donde estoy parado contra la vm
      vm2elias.vm.synced_folder 'compartido_Host2/', '/home/vagrant/compartido'
  
    # Agrega la key Privada de ssh en .vagrant/machines/default/virtualbox/private_key
    vm2elias.ssh.insert_key = true
    vm2elias.vm.provider "virtualbox" do |vb2|
      vb2.memory = "1024"
      vb2.name = "vm2elias"
      vb2.cpus = 1
      vb2.linked_clone = true
      # Seteo controladora Grafica
      vb2.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    end
    
    
    # Puedo Ejecutar un script que esta en un archivo
    vm2elias.vm.provision "shell", path: "script_Enable_ssh_password.sh"
    
    # Provisión para instalar
    vm2elias.vm.provision "shell", inline: <<-SHELL
      dnf install -y /home/vagrant/compartido/tree-1.8.0-10.el9.x86_64.rpm

      subscription-manager repos --enable codeready-builder-for-rhel-9-$(arch)-rpms
      dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    SHELL
  end
end
